In [281]:
import torch
from tqdm.auto import tqdm
from EmotionModel import EmotionModel

In [282]:
dtype = torch.float32
device: str = "mps"

In [283]:
def dummy_representation_generator() -> torch.tensor:
    return torch.clamp(torch.rand(7, dtype=dtype, device=device), -1, 1)

In [284]:
# key
representation: torch.tensor = torch.softmax(dummy_representation_generator(), dim=0, dtype=dtype)
representation

tensor([0.0782, 0.1151, 0.0839, 0.2028, 0.1703, 0.1798, 0.1699],
       device='mps:0')

In [285]:
representation = torch.diag(representation)
representation

tensor([[0.0782, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1151, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0839, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.2028, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.1703, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1798, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1699]],
       device='mps:0')

In [286]:
# query
input_emotion: torch.tensor = dummy_representation_generator()
input_emotion

tensor([0.5260, 0.0833, 0.4468, 0.5620, 0.0570, 0.1224, 0.3910],
       device='mps:0')

In [287]:
model = EmotionModel("dot_product")

In [288]:
new_representation = model.forward(representation, input_emotion)

In [289]:
new_representation

tensor([-0.1518, -0.2973,  0.0901,  0.1285,  0.1176,  0.2459,  0.1481],
       grad_fn=<ClampBackward1>)

In [290]:
torch.argmax(new_representation)

tensor(5)