In [1]:
import torch
from SimilarityAnalyser import SimilarityAnalyser

In [2]:
dtype = torch.float32
device: str = "cpu"

In [3]:
def dummy_representation_generator() -> torch.tensor:
    return torch.clamp(torch.rand(7, dtype=dtype, device=device), -1, 1)

In [4]:
representations: list[torch.tensor] = [dummy_representation_generator() for _ in range(7)]
representations

[tensor([0.7290, 0.2511, 0.4525, 0.3009, 0.5804, 0.9012, 0.7485]),
 tensor([0.1633, 0.8735, 0.3068, 0.6218, 0.8081, 0.8080, 0.4277]),
 tensor([0.4205, 0.1770, 0.1013, 0.3882, 0.3320, 0.7522, 0.3223]),
 tensor([0.6203, 0.4937, 0.7826, 0.8575, 0.3066, 0.7256, 0.9034]),
 tensor([0.2746, 0.3678, 0.3002, 0.4593, 0.5033, 0.9030, 0.2519]),
 tensor([0.6064, 0.3059, 0.8007, 0.6375, 0.7155, 0.1282, 0.5559]),
 tensor([0.8948, 0.7201, 0.7954, 0.3909, 0.9685, 0.0663, 0.2052])]

In [5]:
ideal_representation: torch.tensor = dummy_representation_generator()
ideal_representation

tensor([0.2547, 0.7189, 0.8889, 0.1536, 0.0043, 0.1318, 0.7354])

In [6]:
analyser = SimilarityAnalyser(0.8, dtype=dtype, device=device)

In [7]:
analyser(representations, ideal_representation)

tensor([0.7608, 0.7485, 0.3693, 1.0757, 0.5007, 0.8255, 0.8581])

In [8]:
analyser.get_max_similarity()

0.7608038187026978

In [9]:
analyser.get_most_similar_representation()

{'representations': [0.7290189862251282,
  0.251118540763855,
  0.45251137018203735,
  0.30093586444854736,
  0.5804073810577393,
  0.9011753797531128,
  0.7484846711158752],
 'similarity': 0.7608038187026978}

In [10]:
analyser.get_most_similar_representation_index()

0