In [1]:
import torch
from SimilarityAnalyser import SimilarityAnalyser

In [2]:
dtype = torch.float32
device: str = "cpu"

In [3]:
def dummy_representation_generator() -> torch.tensor:
    return torch.clamp(torch.rand(7, dtype=dtype, device=device), -1, 1)

In [4]:
representations: list[torch.tensor] = [dummy_representation_generator() for _ in range(7)]
representations

[tensor([0.8217, 0.2798, 0.2414, 0.3736, 0.4314, 0.0925, 0.1266]),
 tensor([0.1031, 0.6175, 0.3619, 0.3477, 0.1677, 0.9407, 0.4888]),
 tensor([0.0542, 0.7901, 0.2594, 0.4039, 0.9206, 0.6410, 0.8666]),
 tensor([0.7071, 0.2724, 0.6894, 0.8019, 0.4792, 0.6290, 0.7689]),
 tensor([0.9204, 0.1526, 0.7518, 0.5034, 0.8640, 0.9854, 0.5827]),
 tensor([0.9763, 0.8896, 0.3347, 0.9345, 0.5914, 0.2590, 0.4803]),
 tensor([0.0545, 0.7564, 0.7842, 0.9407, 0.7005, 0.5920, 0.9107])]

In [5]:
ideal_representation: torch.tensor = dummy_representation_generator()
ideal_representation

tensor([0.7336, 0.6280, 0.9341, 0.7592, 0.4753, 0.5371, 0.2454])

In [6]:
analyser = SimilarityAnalyser(0.4, dtype=dtype, device=device)

In [7]:
analyser(representations, ideal_representation)

tensor([0.5323, 0.5989, 0.7035, 0.9124, 0.9940, 0.9591, 0.9595])

In [8]:
analyser.get_max_similarity()

0

In [9]:
analyser.get_most_similar_representation()

{'representations': [], 'similarity': 0}

In [10]:
analyser.get_most_similar_representation_index()

[]