In [75]:
import torch

a = torch.rand(7)

In [76]:
a

tensor([0.8513, 0.4354, 0.2082, 0.6063, 0.1916, 0.4476, 0.1020])

In [78]:
torch.softmax(a, dim=0)

tensor([0.2162, 0.1426, 0.1136, 0.1692, 0.1118, 0.1444, 0.1022])

In [81]:
from libs.Attention import diagonal_softmax

torch.sum(diagonal_softmax(a.diag()), dim=1)

tensor([0.2162, 0.1426, 0.1136, 0.1692, 0.1118, 0.1444, 0.1022])

In [83]:
b = a.unsqueeze(dim=-1)

In [84]:
b.shape

torch.Size([7, 1])

In [85]:
c = torch.rand((7, 7))

In [86]:
c

tensor([[0.4443, 0.3169, 0.2581, 0.3489, 0.1448, 0.2292, 0.9881],
        [0.4161, 0.2990, 0.4121, 0.8731, 0.2998, 0.6561, 0.2147],
        [0.7162, 0.5696, 0.2185, 0.5104, 0.2159, 0.6640, 0.2287],
        [0.9769, 0.8712, 0.0758, 0.8497, 0.8327, 0.5244, 0.8204],
        [0.3970, 0.2779, 0.9599, 0.2896, 0.0038, 0.7283, 0.6736],
        [0.2010, 0.6260, 0.1427, 0.0389, 0.0265, 0.0323, 0.3480],
        [0.5493, 0.1155, 0.5764, 0.1937, 0.9185, 0.8141, 0.3300]])

In [92]:
torch.argmax(c, dim=1)

tensor([6, 3, 0, 0, 2, 1, 4])

In [87]:
a + c

tensor([[1.2957, 0.7523, 0.4663, 0.9552, 0.3363, 0.6768, 1.0901],
        [1.2675, 0.7344, 0.6203, 1.4794, 0.4914, 1.1037, 0.3167],
        [1.5676, 1.0050, 0.4267, 1.1167, 0.4074, 1.1116, 0.3307],
        [1.8282, 1.3066, 0.2840, 1.4560, 1.0243, 0.9720, 0.9225],
        [1.2483, 0.7133, 1.1680, 0.8960, 0.1953, 1.1759, 0.7756],
        [1.0523, 1.0614, 0.3509, 0.6453, 0.2180, 0.4799, 0.4500],
        [1.4006, 0.5509, 0.7846, 0.8000, 1.1101, 1.2617, 0.4321]])

In [91]:
torch.sum(c[1])

tensor(3.1709)

In [89]:
torch.sum(c, dim=1)

tensor([2.7302, 3.1709, 3.1232, 4.9512, 3.3300, 1.4154, 3.4976])

In [93]:
t = [1, 2, 3]

In [95]:
torch.nn.functional.one_hot(torch.tensor(t), 7)

tensor([[0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0]])